# Generated by Django 4.0.6 on 2022-07-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isuser',
            name='gender',
            field=models.IntegerField(default='Not to say', verbose_name=('Female', 'Male', 'Other')),
        ),
    ]
