# Generated by Django 4.0.6 on 2022-07-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_isuser_options_alter_isuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isuser',
            name='image',
            field=models.ImageField(default='/profile_image/unknown.jpg', upload_to='profile_image/'),
        ),
    ]
